import {
  Wifi,
  Waves,
  Dumbbell,
  Car,
  PawPrint,
  Tv,
  Thermometer,
  CigaretteOff,
  Cable,
  Maximize,
  Bath,
  Phone,
  Sprout,
  Hammer,
  Bus,
  Mountain,
  VolumeX,
  Home,
  Warehouse,
  Building,
  Castle,
  Trees,
  LucideIcon,
  Shield,
  Lock,
  Binoculars,
  Wrench,
  Flame,
  Accessibility,
  ArrowUp,
  ArrowUpDown,
  Box,
  House,
  Sparkles,
  Armchair,
  Rows3,
  BriefcaseBusiness,
  Trophy,
  WashingMachine,
  Shapes,
  DoorOpen,
  MapPinHouse,
  TreePine,
  Users,
  Building2,
  HouseWifi,
  AlarmSmoke,
  Cctv,
  FireExtinguisher,
  Fence,
  Leaf,
  Hospital,
  University,
} from "lucide-react";

export enum AmenityEnum {
  WasherDryer = "WasherDryer",
  AirConditioning = "AirConditioning",
  Dishwasher = "Dishwasher",
  HighSpeedInternet = "HighSpeedInternet",
  HardwoodFloors = "HardwoodFloors",
  WalkInClosets = "WalkInClosets",
  Microwave = "Microwave",
  Refrigerator = "Refrigerator",
  Pool = "Pool",
  Gym = "Gym",
  Parking = "Parking",
  PetsAllowed = "PetsAllowed",
  WiFi = "WiFi",

  Heating = "Heating",
  CableReady = "CableReady",
  SatelliteTV = "SatelliteTV",
  SmokeFree = "SmokeFree",
  WheelchairAccessible = "WheelchairAccessible",
  BalconyOrPatio = "BalconyOrPatio",
  Fireplace = "Fireplace",
  SecuritySystem = "SecuritySystem",
  Elevator = "Elevator",
  Furnished = "Furnished",
  Storage = "Storage",
  LaundryFacilities = "LaundryFacilities",
  CommunityLounge = "CommunityLounge",
  BusinessCenter = "BusinessCenter",
  Playground = "Playground",
  BarbecueArea = "BarbecueArea",
  TennisCourt = "TennisCourt",
  Clubhouse = "Clubhouse",
  Spa = "Spa",
  RooftopAccess = "RooftopAccess",

  FireExtinguisher = "FireExtinguisher",
  SmokeDetectors = "SmokeDetectors",
  SolarPanels = "SolarPanels",
  Garden = "Garden",
  SecurityCameras = "SecurityCameras",
}

export const AmenityIcons: Record<AmenityEnum, LucideIcon> = {
  WasherDryer: Waves,
  AirConditioning: Thermometer,
  Dishwasher: Waves,
  HighSpeedInternet: Wifi,
  HardwoodFloors: Home,
  WalkInClosets: Maximize,
  Microwave: Tv,
  Refrigerator: Thermometer,
  Pool: Waves,
  Gym: Dumbbell,
  Parking: Car,
  PetsAllowed: PawPrint,
  WiFi: Wifi,

  Heating: Thermometer,
  CableReady: Cable,
  SatelliteTV: Tv,
  SmokeFree: CigaretteOff,
  WheelchairAccessible: Accessibility,
  BalconyOrPatio: Maximize,
  Fireplace: Flame,
  SecuritySystem: Shield,
  Elevator: ArrowUpDown,
  Furnished: Home,
  Storage: Box,
  LaundryFacilities: WashingMachine,
  CommunityLounge: Armchair,
  BusinessCenter: BriefcaseBusiness,
  Playground: Shapes,
  BarbecueArea: Rows3,
  TennisCourt: Trophy,
  Clubhouse: House,
  Spa: Sparkles,
  RooftopAccess: ArrowUp,

  FireExtinguisher: FireExtinguisher,
  SmokeDetectors: AlarmSmoke,
  SolarPanels: Leaf,
  Garden: Fence,
  SecurityCameras: Cctv,
};

export enum HighlightEnum {
  HighSpeedInternetAccess = "HighSpeedInternetAccess",
  WasherDryer = "WasherDryer",
  AirConditioning = "AirConditioning",
  Heating = "Heating",
  SmokeFree = "SmokeFree",
  CableReady = "CableReady",
  SatelliteTV = "SatelliteTV",
  DoubleVanities = "DoubleVanities",
  TubShower = "TubShower",
  Intercom = "Intercom",
  SprinklerSystem = "SprinklerSystem",
  RecentlyRenovated = "RecentlyRenovated",
  CloseToTransit = "CloseToTransit",
  GreatView = "GreatView",
  QuietNeighborhood = "QuietNeighborhood",

  WheelchairAccessible = "WheelchairAccessible",
  BalconyOrPatio = "BalconyOrPatio",
  Fireplace = "Fireplace",
  PrivateEntrance = "PrivateEntrance",
  SmartHomeFeatures = "SmartHomeFeatures",
  EnergyEfficientAppliances = "EnergyEfficientAppliances",
  GatedCommunity = "GatedCommunity",
  RooftopAccess = "RooftopAccess",
  SecureParking = "SecureParking",
  OnSiteManagement = "OnSiteManagement",
  PetFriendly = "PetFriendly",
  BalconyView = "BalconyView",
  ModernAppliances = "ModernAppliances",

  NearSchool = "NearSchool",
  NearHospital = "NearHospital",
}

export const HighlightIcons: Record<HighlightEnum, LucideIcon> = {
  HighSpeedInternetAccess: Wifi,
  WasherDryer: Waves,
  AirConditioning: Thermometer,
  Heating: Thermometer,
  SmokeFree: CigaretteOff,
  CableReady: Cable,
  SatelliteTV: Tv,
  DoubleVanities: Maximize,
  TubShower: Bath,
  Intercom: Phone,
  SprinklerSystem: Sprout,
  RecentlyRenovated: Hammer,
  CloseToTransit: Bus,
  GreatView: Mountain,
  QuietNeighborhood: VolumeX,

  WheelchairAccessible: Accessibility,
  BalconyOrPatio: Maximize,
  Fireplace: Flame,
  PrivateEntrance: DoorOpen,
  SmartHomeFeatures: HouseWifi,
  EnergyEfficientAppliances: Wrench,
  GatedCommunity: Lock,
  RooftopAccess: ArrowUp,
  SecureParking: Lock,
  OnSiteManagement: Building2,
  PetFriendly: PawPrint,
  BalconyView: Binoculars,
  ModernAppliances: Wrench,

  NearSchool: University,
  NearHospital: Hospital,
};

export enum PropertyTypeEnum {
  Rooms = "Rooms",
  TinyHouse = "TinyHouse",
  Apartment = "Apartment",
  Villa = "Villa",
  Townhouse = "Townhouse",
  Cottage = "Cottage",

  Studio = "Studio",
  Duplex = "Duplex",
  Penthouse = "Penthouse",
  Bungalow = "Bungalow",
  Farmhouse = "Farmhouse",
  CoLivingSpace = "CoLivingSpace",
}

export const PropertyTypeIcons: Record<PropertyTypeEnum, LucideIcon> = {
  Rooms: Home,
  TinyHouse: Warehouse,
  Apartment: Building,
  Villa: Castle,
  Townhouse: Home,
  Cottage: Trees,

  Studio: Home,
  Duplex: Building,
  Penthouse: MapPinHouse,
  Bungalow: TreePine,
  Farmhouse: Trees,
  CoLivingSpace: Users,
};

// Add this constant at the end of the file
export const NAVBAR_HEIGHT = 52; // in pixels

// Test users for development
export const testUsers = {
  tenant: {
    username: "Carol White",
    userId: "us-east-2:76543210-90ab-cdef-1234-567890abcdef",
    signInDetails: {
      loginId: "carol.white@example.com",
      authFlowType: "USER_SRP_AUTH",
    },
  },
  tenantRole: "tenant",
  manager: {
    username: "John Smith",
    userId: "us-east-2:12345678-90ab-cdef-1234-567890abcdef",
    signInDetails: {
      loginId: "john.smith@example.com",
      authFlowType: "USER_SRP_AUTH",
    },
  },
  managerRole: "manager",
};
